#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "y4zgr/zL4pWj"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 11
#define HCS(report) host_consumer_send(record->event.pressed ? report : 0); return false

#define WHEEL_EXTENDED_SUPPORT
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 1
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#define MOUSE_EXTENDED_REPORT
#define NAVIGATOR_SCROLL_DIVIDER 50

#define RGB_MATRIX_STARTUP_SPD 60

